import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/Home/Banner/Banner";
import Known from "@/components/Home/Known/Known";
import About from "@/components/Home/About";
import HowWorks from "@/components/Home/HowWorks";
import Register from "@/components/Home/Register";
import Repositories from "@/components/Github/Github";

// const inter = Inter({ subsets: ["latin"] });
import { useSelector } from "react-redux";
import { SessionProvider, useSession } from 'next-auth/react';



export default function Home() {
  const { user } = useSelector((state) => state.register);
  return (
    <>
      <Head>
        <title>SilverSitting - Seniors take care of children</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="../styles/Header.css" />
      </Head>
      <main>


      <SessionProvider>
        <Repositories/>
    </SessionProvider>
        
        <Banner />
        <Known />
        <About />
        <HowWorks />
        {!user && <Register />}
      </main>
    </>
  );
}
